import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateEmailCoreTables1765434144524 implements MigrationInterface {
    name = 'CreateEmailCoreTables1765434144524'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "deal_products" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "dealId" uuid NOT NULL, "name" character varying(255) NOT NULL, "description" text, "sku" character varying(100), "quantity" integer NOT NULL DEFAULT '1', "price" numeric(15,2) NOT NULL, "discount" numeric(5,2) NOT NULL DEFAULT '0', "total" numeric(15,2) NOT NULL, "currency" character varying(10) NOT NULL DEFAULT 'USD', CONSTRAINT "PK_37d93e833e461dc00720be123dd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d24a6d626a445743f51f721f22" ON "deal_products" ("dealId") `);
        await queryRunner.query(`CREATE TYPE "public"."email_templates_engine_enum" AS ENUM('mjml')`);
        await queryRunner.query(`CREATE TABLE "email_templates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "tenantId" uuid, "name" character varying(150) NOT NULL, "slug" character varying(150) NOT NULL, "engine" "public"."email_templates_engine_enum" NOT NULL DEFAULT 'mjml', "subjectTemplate" character varying(255) NOT NULL, "mjmlTemplate" text NOT NULL, "textTemplate" text, "variablesSchema" jsonb, "isActive" boolean NOT NULL DEFAULT true, "metadata" jsonb, CONSTRAINT "PK_06c564c515d8cdb40b6f3bfbbb4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9bbba723be40ebdd6c93587a99" ON "email_templates" ("tenantId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_9e28c9e5f18f5ddfd6695c7243" ON "email_templates" ("tenantId", "slug") `);
        await queryRunner.query(`CREATE TYPE "public"."email_events_type_enum" AS ENUM('queued', 'sending', 'sent', 'failed', 'delivered', 'open', 'click', 'bounce', 'complaint')`);
        await queryRunner.query(`CREATE TABLE "email_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "emailMessageId" uuid NOT NULL, "type" "public"."email_events_type_enum" NOT NULL, "occurredAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "ip" character varying(45), "userAgent" text, "metadata" jsonb, CONSTRAINT "PK_2ab38c98c3ca9385eff428134c2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5f6fe5c6c83b2fc28869dcebe9" ON "email_events" ("emailMessageId") `);
        await queryRunner.query(`CREATE TABLE "email_links" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "emailMessageId" uuid NOT NULL, "token" character varying(50) NOT NULL, "originalUrl" text NOT NULL, "clickCount" integer NOT NULL DEFAULT '0', "firstClickedAt" TIMESTAMP WITH TIME ZONE, "lastClickedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_1f3c70dc8e6738f8b4c45db9745" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cd7a7ea0bccbbcd8e6c4e99773" ON "email_links" ("emailMessageId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_112aebd3488820713029fe0494" ON "email_links" ("token") `);
        await queryRunner.query(`CREATE TYPE "public"."email_messages_provider_enum" AS ENUM('smtp', 'ses')`);
        await queryRunner.query(`CREATE TYPE "public"."email_messages_status_enum" AS ENUM('queued', 'sending', 'sent', 'failed', 'delivered', 'bounced', 'complained')`);
        await queryRunner.query(`CREATE TABLE "email_messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "tenantId" uuid NOT NULL, "createdByUserId" uuid NOT NULL, "templateId" uuid, "fromEmail" character varying(255), "fromName" character varying(255), "replyTo" character varying(255), "to" text array NOT NULL, "cc" text array NOT NULL DEFAULT ARRAY[]::text[], "bcc" text array NOT NULL DEFAULT ARRAY[]::text[], "subject" character varying(255) NOT NULL, "html" text NOT NULL, "text" text, "provider" "public"."email_messages_provider_enum" NOT NULL DEFAULT 'smtp', "providerMessageId" character varying(255), "status" "public"."email_messages_status_enum" NOT NULL DEFAULT 'queued', "sentAt" TIMESTAMP WITH TIME ZONE, "deliveredAt" TIMESTAMP WITH TIME ZONE, "failedAt" TIMESTAMP WITH TIME ZONE, "errorMessage" text, "openCount" integer NOT NULL DEFAULT '0', "clickCount" integer NOT NULL DEFAULT '0', "firstOpenedAt" TIMESTAMP WITH TIME ZONE, "lastOpenedAt" TIMESTAMP WITH TIME ZONE, "firstClickedAt" TIMESTAMP WITH TIME ZONE, "lastClickedAt" TIMESTAMP WITH TIME ZONE, "leadId" uuid, "contactId" uuid, "companyId" uuid, "dealId" uuid, "metadata" jsonb, CONSTRAINT "PK_922cad79d5a315f5d1d06b077da" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_70618e43b6911a0dce36a99994" ON "email_messages" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d9ea8a7266a0afe29670ed353a" ON "email_messages" ("createdByUserId") `);
        await queryRunner.query(`CREATE INDEX "IDX_927125064754350c0de20fb7a4" ON "email_messages" ("templateId") `);
        await queryRunner.query(`CREATE INDEX "IDX_37dacf7493939d020f5667a590" ON "email_messages" ("providerMessageId") `);
        await queryRunner.query(`CREATE INDEX "IDX_053145c3bb6387377348b24ab1" ON "email_messages" ("leadId") `);
        await queryRunner.query(`CREATE INDEX "IDX_7d0fb3250b2c909c1801a5a779" ON "email_messages" ("contactId") `);
        await queryRunner.query(`CREATE INDEX "IDX_15d775752e1835c52122b8264b" ON "email_messages" ("companyId") `);
        await queryRunner.query(`CREATE INDEX "IDX_13b274d0adaf22858c74cd9071" ON "email_messages" ("dealId") `);
        await queryRunner.query(`ALTER TABLE "custom_field_values" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "custom_field_values" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "deals" DROP COLUMN "closeDate"`);
        await queryRunner.query(`CREATE TYPE "public"."activities_priority_enum" AS ENUM('low', 'medium', 'high', 'urgent')`);
        await queryRunner.query(`ALTER TABLE "activities" ADD "priority" "public"."activities_priority_enum" NOT NULL DEFAULT 'medium'`);
        await queryRunner.query(`ALTER TABLE "activities" ADD "startDate" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "activities" ADD "endDate" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "activities" ADD "duration" integer`);
        await queryRunner.query(`ALTER TABLE "activities" ADD "assignedToId" uuid`);
        await queryRunner.query(`ALTER TABLE "activities" ADD "location" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "activities" ADD "attendees" jsonb`);
        await queryRunner.query(`ALTER TABLE "activities" ADD "isAllDay" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "activities" ADD "outcome" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "activities" ADD "reminderMinutes" integer`);
        await queryRunner.query(`ALTER TABLE "custom_field_values" ADD "dealId" uuid`);
        await queryRunner.query(`CREATE TYPE "public"."deals_priority_enum" AS ENUM('low', 'medium', 'high', 'critical')`);
        await queryRunner.query(`ALTER TABLE "deals" ADD "priority" "public"."deals_priority_enum" NOT NULL DEFAULT 'medium'`);
        await queryRunner.query(`ALTER TABLE "deals" ADD "expectedCloseDate" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "deals" ADD "actualCloseDate" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "deals" ADD "source" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "deals" ADD "tags" jsonb NOT NULL DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "deals" ADD "products" jsonb`);
        await queryRunner.query(`ALTER TABLE "deals" ADD "lastActivityAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "deals" ADD "daysInStage" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "deals" ADD "totalDaysInPipeline" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TYPE "public"."activities_type_enum" RENAME TO "activities_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."activities_type_enum" AS ENUM('call', 'meeting', 'task', 'note', 'email', 'sms', 'deadline', 'lunch')`);
        await queryRunner.query(`ALTER TABLE "activities" ALTER COLUMN "type" TYPE "public"."activities_type_enum" USING "type"::"text"::"public"."activities_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."activities_type_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."activities_status_enum" RENAME TO "activities_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."activities_status_enum" AS ENUM('scheduled', 'in_progress', 'completed', 'cancelled', 'overdue')`);
        await queryRunner.query(`ALTER TABLE "activities" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "activities" ALTER COLUMN "status" TYPE "public"."activities_status_enum" USING "status"::"text"::"public"."activities_status_enum"`);
        await queryRunner.query(`ALTER TABLE "activities" ALTER COLUMN "status" SET DEFAULT 'scheduled'`);
        await queryRunner.query(`DROP TYPE "public"."activities_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "activities" ALTER COLUMN "dueDate" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "deals" ALTER COLUMN "amount" SET DEFAULT '0'`);
        await queryRunner.query(`CREATE INDEX "IDX_d70c223183f4b3fe5a8fbd6772" ON "activities" ("assignedToId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e1cd35bc64fd8b4b11b2cd43a0" ON "custom_field_values" ("dealId") `);
        await queryRunner.query(`ALTER TABLE "activities" ADD CONSTRAINT "FK_d70c223183f4b3fe5a8fbd6772c" FOREIGN KEY ("assignedToId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "custom_field_values" ADD CONSTRAINT "FK_e1cd35bc64fd8b4b11b2cd43a03" FOREIGN KEY ("dealId") REFERENCES "deals"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "deal_products" ADD CONSTRAINT "FK_d24a6d626a445743f51f721f226" FOREIGN KEY ("dealId") REFERENCES "deals"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "email_templates" ADD CONSTRAINT "FK_9bbba723be40ebdd6c93587a997" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "email_events" ADD CONSTRAINT "FK_5f6fe5c6c83b2fc28869dcebe99" FOREIGN KEY ("emailMessageId") REFERENCES "email_messages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "email_links" ADD CONSTRAINT "FK_cd7a7ea0bccbbcd8e6c4e99773d" FOREIGN KEY ("emailMessageId") REFERENCES "email_messages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "email_messages" ADD CONSTRAINT "FK_70618e43b6911a0dce36a99994a" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "email_messages" ADD CONSTRAINT "FK_d9ea8a7266a0afe29670ed353a9" FOREIGN KEY ("createdByUserId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "email_messages" ADD CONSTRAINT "FK_927125064754350c0de20fb7a40" FOREIGN KEY ("templateId") REFERENCES "email_templates"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "email_messages" ADD CONSTRAINT "FK_053145c3bb6387377348b24ab1d" FOREIGN KEY ("leadId") REFERENCES "leads"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "email_messages" ADD CONSTRAINT "FK_7d0fb3250b2c909c1801a5a7793" FOREIGN KEY ("contactId") REFERENCES "contacts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "email_messages" ADD CONSTRAINT "FK_15d775752e1835c52122b8264b9" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "email_messages" ADD CONSTRAINT "FK_13b274d0adaf22858c74cd9071d" FOREIGN KEY ("dealId") REFERENCES "deals"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "email_messages" DROP CONSTRAINT "FK_13b274d0adaf22858c74cd9071d"`);
        await queryRunner.query(`ALTER TABLE "email_messages" DROP CONSTRAINT "FK_15d775752e1835c52122b8264b9"`);
        await queryRunner.query(`ALTER TABLE "email_messages" DROP CONSTRAINT "FK_7d0fb3250b2c909c1801a5a7793"`);
        await queryRunner.query(`ALTER TABLE "email_messages" DROP CONSTRAINT "FK_053145c3bb6387377348b24ab1d"`);
        await queryRunner.query(`ALTER TABLE "email_messages" DROP CONSTRAINT "FK_927125064754350c0de20fb7a40"`);
        await queryRunner.query(`ALTER TABLE "email_messages" DROP CONSTRAINT "FK_d9ea8a7266a0afe29670ed353a9"`);
        await queryRunner.query(`ALTER TABLE "email_messages" DROP CONSTRAINT "FK_70618e43b6911a0dce36a99994a"`);
        await queryRunner.query(`ALTER TABLE "email_links" DROP CONSTRAINT "FK_cd7a7ea0bccbbcd8e6c4e99773d"`);
        await queryRunner.query(`ALTER TABLE "email_events" DROP CONSTRAINT "FK_5f6fe5c6c83b2fc28869dcebe99"`);
        await queryRunner.query(`ALTER TABLE "email_templates" DROP CONSTRAINT "FK_9bbba723be40ebdd6c93587a997"`);
        await queryRunner.query(`ALTER TABLE "deal_products" DROP CONSTRAINT "FK_d24a6d626a445743f51f721f226"`);
        await queryRunner.query(`ALTER TABLE "custom_field_values" DROP CONSTRAINT "FK_e1cd35bc64fd8b4b11b2cd43a03"`);
        await queryRunner.query(`ALTER TABLE "activities" DROP CONSTRAINT "FK_d70c223183f4b3fe5a8fbd6772c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e1cd35bc64fd8b4b11b2cd43a0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d70c223183f4b3fe5a8fbd6772"`);
        await queryRunner.query(`ALTER TABLE "deals" ALTER COLUMN "amount" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "activities" ALTER COLUMN "dueDate" SET NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."activities_status_enum_old" AS ENUM('scheduled', 'completed', 'cancelled', 'overdue')`);
        await queryRunner.query(`ALTER TABLE "activities" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "activities" ALTER COLUMN "status" TYPE "public"."activities_status_enum_old" USING "status"::"text"::"public"."activities_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "activities" ALTER COLUMN "status" SET DEFAULT 'scheduled'`);
        await queryRunner.query(`DROP TYPE "public"."activities_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."activities_status_enum_old" RENAME TO "activities_status_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."activities_type_enum_old" AS ENUM('call', 'meeting', 'task', 'note', 'email', 'sms')`);
        await queryRunner.query(`ALTER TABLE "activities" ALTER COLUMN "type" TYPE "public"."activities_type_enum_old" USING "type"::"text"::"public"."activities_type_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."activities_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."activities_type_enum_old" RENAME TO "activities_type_enum"`);
        await queryRunner.query(`ALTER TABLE "deals" DROP COLUMN "totalDaysInPipeline"`);
        await queryRunner.query(`ALTER TABLE "deals" DROP COLUMN "daysInStage"`);
        await queryRunner.query(`ALTER TABLE "deals" DROP COLUMN "lastActivityAt"`);
        await queryRunner.query(`ALTER TABLE "deals" DROP COLUMN "products"`);
        await queryRunner.query(`ALTER TABLE "deals" DROP COLUMN "tags"`);
        await queryRunner.query(`ALTER TABLE "deals" DROP COLUMN "source"`);
        await queryRunner.query(`ALTER TABLE "deals" DROP COLUMN "actualCloseDate"`);
        await queryRunner.query(`ALTER TABLE "deals" DROP COLUMN "expectedCloseDate"`);
        await queryRunner.query(`ALTER TABLE "deals" DROP COLUMN "priority"`);
        await queryRunner.query(`DROP TYPE "public"."deals_priority_enum"`);
        await queryRunner.query(`ALTER TABLE "custom_field_values" DROP COLUMN "dealId"`);
        await queryRunner.query(`ALTER TABLE "activities" DROP COLUMN "reminderMinutes"`);
        await queryRunner.query(`ALTER TABLE "activities" DROP COLUMN "outcome"`);
        await queryRunner.query(`ALTER TABLE "activities" DROP COLUMN "isAllDay"`);
        await queryRunner.query(`ALTER TABLE "activities" DROP COLUMN "attendees"`);
        await queryRunner.query(`ALTER TABLE "activities" DROP COLUMN "location"`);
        await queryRunner.query(`ALTER TABLE "activities" DROP COLUMN "assignedToId"`);
        await queryRunner.query(`ALTER TABLE "activities" DROP COLUMN "duration"`);
        await queryRunner.query(`ALTER TABLE "activities" DROP COLUMN "endDate"`);
        await queryRunner.query(`ALTER TABLE "activities" DROP COLUMN "startDate"`);
        await queryRunner.query(`ALTER TABLE "activities" DROP COLUMN "priority"`);
        await queryRunner.query(`DROP TYPE "public"."activities_priority_enum"`);
        await queryRunner.query(`ALTER TABLE "deals" ADD "closeDate" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "custom_field_values" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "custom_field_values" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`DROP INDEX "public"."IDX_13b274d0adaf22858c74cd9071"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_15d775752e1835c52122b8264b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7d0fb3250b2c909c1801a5a779"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_053145c3bb6387377348b24ab1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_37dacf7493939d020f5667a590"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_927125064754350c0de20fb7a4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d9ea8a7266a0afe29670ed353a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_70618e43b6911a0dce36a99994"`);
        await queryRunner.query(`DROP TABLE "email_messages"`);
        await queryRunner.query(`DROP TYPE "public"."email_messages_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."email_messages_provider_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_112aebd3488820713029fe0494"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cd7a7ea0bccbbcd8e6c4e99773"`);
        await queryRunner.query(`DROP TABLE "email_links"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5f6fe5c6c83b2fc28869dcebe9"`);
        await queryRunner.query(`DROP TABLE "email_events"`);
        await queryRunner.query(`DROP TYPE "public"."email_events_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9e28c9e5f18f5ddfd6695c7243"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9bbba723be40ebdd6c93587a99"`);
        await queryRunner.query(`DROP TABLE "email_templates"`);
        await queryRunner.query(`DROP TYPE "public"."email_templates_engine_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d24a6d626a445743f51f721f22"`);
        await queryRunner.query(`DROP TABLE "deal_products"`);
    }

}
